version: '2'
services:
  vrt-server:
    image: omelhoro1/vrt-server
    container_name: vrt-server
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    labels:
      - "traefik.frontend.rule=Host:vrt-server.igor-fischer.rocks,vrt-server.fischerops.com"
    volumes:
      - /usr/captain/vrt-pictures:/app/pictures
    environment:
      - VIRTUAL_HOST=vrt-server.igor-fischer.rocks,vrt-server.fischerops.com
      - LETSENCRYPT_HOST=vrt-server.igor-fischer.rocks,vrt-server.fischerops.com
      - CURRENT_URL=vrt-server.igor-fischer.rocks
      - VAULT_PASS=${VAULT_PASS}
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=fischerig@outlook.com
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
